################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/BLE \
Drivers/BLE/stm32wb_at \
Drivers/CatM1 \
Drivers/ST7789 \
Drivers/STM32U5xx_HAL_Driver/Src \
Drivers/audio \
Drivers/pmic/MAX20303 \
Drivers/pmic \
Drivers/sensorhub \
Drivers/touch/BL6133 \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
TouchGFX/App \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/charging_screen_screen \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/containers \
TouchGFX/generated/gui_generated/src/deviceinfosetting_screen \
TouchGFX/generated/gui_generated/src/falldetected_screen \
TouchGFX/generated/gui_generated/src/flashlight_screen_screen \
TouchGFX/generated/gui_generated/src/heartratedetail_screen \
TouchGFX/generated/gui_generated/src/heartratescreen_screen \
TouchGFX/generated/gui_generated/src/homescreenwithbiodata_screen \
TouchGFX/generated/gui_generated/src/informationsetting_screen \
TouchGFX/generated/gui_generated/src/initblackscreen_screen \
TouchGFX/generated/gui_generated/src/languagesetting_screen \
TouchGFX/generated/gui_generated/src/networkinfosetting_screen \
TouchGFX/generated/gui_generated/src/screenbrightnesssetting_screen \
TouchGFX/generated/gui_generated/src/screenontimesetting_screen \
TouchGFX/generated/gui_generated/src/screensetting_screen \
TouchGFX/generated/gui_generated/src/settingscreen_screen \
TouchGFX/generated/gui_generated/src/sleepscreen_screen \
TouchGFX/generated/gui_generated/src/sos_alert_screen \
TouchGFX/generated/gui_generated/src/soundnhapticssetting_screen \
TouchGFX/generated/gui_generated/src/spo2detail_screen \
TouchGFX/generated/gui_generated/src/spo2screen_screen \
TouchGFX/generated/gui_generated/src/stepsscreen_screen \
TouchGFX/generated/gui_generated/src/swipedownfromhome_screen \
TouchGFX/generated/gui_generated/src/systemsetting_screen \
TouchGFX/generated/gui_generated/src/temphome_screen \
TouchGFX/generated/gui_generated/src/turnoffscreen_screen \
TouchGFX/generated/gui_generated/src/uncharging_screen_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__generated \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/charging_screen_screen \
TouchGFX/gui/src/common \
TouchGFX/gui/src/containers \
TouchGFX/gui/src/deviceinfosetting_screen \
TouchGFX/gui/src/falldetected_screen \
TouchGFX/gui/src/flashlight_screen_screen \
TouchGFX/gui/src/heartratedetail_screen \
TouchGFX/gui/src/heartratescreen_screen \
TouchGFX/gui/src/homescreenwithbiodata_screen \
TouchGFX/gui/src/informationsetting_screen \
TouchGFX/gui/src/initblackscreen_screen \
TouchGFX/gui/src/languagesetting_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/networkinfosetting_screen \
TouchGFX/gui/src/screenbrightnesssetting_screen \
TouchGFX/gui/src/screenontimesetting_screen \
TouchGFX/gui/src/screensetting_screen \
TouchGFX/gui/src/settingscreen_screen \
TouchGFX/gui/src/sleepscreen_screen \
TouchGFX/gui/src/sos_alert_screen \
TouchGFX/gui/src/soundnhapticssetting_screen \
TouchGFX/gui/src/spo2detail_screen \
TouchGFX/gui/src/spo2screen_screen \
TouchGFX/gui/src/stepsscreen_screen \
TouchGFX/gui/src/swipedownfromhome_screen \
TouchGFX/gui/src/systemsetting_screen \
TouchGFX/gui/src/temphome_screen \
TouchGFX/gui/src/turnoffscreen_screen \
TouchGFX/gui/src/uncharging_screen_screen \
TouchGFX/target \
TouchGFX/target/generated \

